[build]
  base = "apps/web"
  command = "npm install -g pnpm && cd ../.. && pnpm install && pnpm turbo run build --filter=web"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
